repos:
  - repo: local
    hooks:
      - id: black-check
        name: Check Python Formatting
        entry: black --check app/
        language: system
        types: [python]
        files: ^app/

      - id: mypy-check
        name: Static Typing with mypy
        entry: mypy --explicit-package-bases app --exclude 'app/__init__\.py$'
        language: system
        types: [python]
        files: ^app/
        pass_filenames: false

      - id: pylint-check
        name: Lint Python with pylint
        entry: pylint
        args: [app/]
        language: system
        types: [python]
        files: ^app/
